/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package battleforhonor;

import controller.corelaucher.CoreLauncher;
import javafx.application.Application;

/**
 * This class is the Main class of the JavaFX-based application.
 * 
 */
public final class BattleForHonorApp {

    /**
     * 
     * @param args unused.
     */
    public static void main(final String[] args) {
       Application.launch(CoreLauncher.class);
    }
    
}


