/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package battleforhonor;

import javafx.application.Application;
import javafx.stage.Stage;

import view.MainMenu;


/** Main application entry-point. */

public final class BattleForHonorApp {


    public static void main(final String[] args) {
        Application.launch(MainMenu.class, args);
    }
}


