/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package battleforhonor;


import controller.StageManager;


/** Main application entry-point. */

public final class BattleForHonorApp {


    public static void main(final String[] args) {
       StageManager.main(args);
    }
}


