/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package model.enemies;

import controller.CoreLauncher;
import javafx.application.Application;

/** Main application entry-point. */

public final class BattleForHonorApp {


    public static void main(final String[] args) {
       Application.launch(CoreLauncher.class);
    }
}


